name = "mattus mods"
author = "Mattu"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c934cceab2621843034dc35e0986b9a35513416e5f7b9ae86156c8361807af7"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
