name = "mattus mods"
author = "Mattu"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb7fcd631d1cbd86fb69a5a8650b9448a7e26f13c189de94c17352401377afd4"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
